# Imports and definitions

In [ ]:
pip install openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 221.4/221.4 kB 4.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 kB 7.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.9/76.9 kB 4.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 5.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
llmx 0.0.15a0 requires cohere, which is not installed.
llmx 0.0.15a0 requires tiktoken, which is not installed.


In [ ]:
#import os
from google.colab import userdata
import openai
import pandas as pd
import re
import time
import numpy as np

client = openai.OpenAI(api_key = userdata.get('OPENAI_API_KEY'))

In [ ]:
dialectDict = {
  "1": "Brt",
  "2": "Sgp",
  "3": "Ind",
  "4": "Aus",
  "5": "Saf",
  "6": "Irs",
  "0": "For",
  "-1": "Nan",
  1: "Irish",
  2: "South African",
  3: "Singaporean",
  4: "Australian",
  5: "Indian",
  6: "British",
  0: "None",
}
reversedDict = {}
for key, value in dialectDict.items():
    reversedDict[value] = key

print(reversedDict)

{'Brt': '1', 'Sgp': '2', 'Ind': '3', 'Aus': '4', 'Saf': '5', 'Irs': '6', 'For': '0', 'Nan': '-1', 'Irish': 1, 'South African': 2, 'Singaporean': 3, 'Australian': 4, 'Indian': 5, 'British': 6, 'None': 0}


#ZeroShot

In [ ]:
def classifyZS(statement):
    response = client.chat.completions.create(
      model="gpt-4",
      messages=[
        {
          "role": "system",
          "content": 'You are a dialectologist specializing in English. Your job is to classify the dialect. The classification labels are:\
          1 = British dialect\
          2 = Singapore dialect\
          3 = Indian dialect\
          4 = Australian dialect\
          5 = South African dialect\
          6 = Irish dialect\
          0 = No dialect\
          Just output the labels'
        },
        {
          "role": "user",
          "content": statement
        }
      ],
      temperature=0,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )
    time.sleep(1)
    label = re.sub("[^0-9]", "", response.choices[0].message.content)
    return label

In [ ]:
accuracy = 0
diaAcc = np.zeros((7,7))

In [ ]:
content = pd.read_csv("datasetWAnno.csv", index_col=None, header=None)

for count, senLabPair in enumerate(content.values):
  label = classifyZS(senLabPair[0])
  #diaAcc[int(reversedDict[senLabPair[1]])][int(label)] += 1
  label = dialectDict[label]
  print(count+1, label, senLabPair[1])
  if label == senLabPair[1] or label == senLabPair[2]
    accuracy += 1

#print(diaAcc)
accuracy_percentage = accuracy / len(content) * 100
print(accuracy_percentage)

1 Irs Irs
2 Brt Irs
3 Brt Irs
4 Brt Irs
5 Irs Irs
6 Irs Irs
7 Irs Irs
8 Irs Irs
9 Irs Irs
10 Irs Irs
11 Irs Irs
12 Irs Irs
13 Brt Irs
14 Irs Irs
15 Brt Irs
16 For Irs
17 For Irs
18 For Irs
19 Irs Irs
20 Brt Irs
21 For Irs
22 For Irs
23 For Irs
24 For Irs
25 For Irs
26 For Irs
27 For Irs
28 Irs Irs
29 Irs Irs
30 Brt Irs
31 Saf Saf
32 Saf Saf
33 Saf Saf
34 Aus Saf
35 Saf Saf
36 Saf Saf
37 Saf Saf
38 Saf Saf
39 For Saf
40 Saf Saf
41 Saf Saf
42 For Saf
43 Aus Saf
44 Brt Saf
45 Brt Saf
46 Brt Saf
47 For Saf
48 For Saf
49 Ind Saf
50 For Saf
51 Saf Saf
52 For Saf
53 Aus Saf
54 For Saf
55 For Saf
56 Saf Saf
57 Saf Saf
58 Saf Saf
59 Brt Saf
60 Saf Saf
61 Sgp Sgp
62 Sgp Sgp
63 Sgp Sgp
64 Sgp Sgp
65 Sgp Sgp
66 Sgp Sgp
67 Sgp Sgp
68 Sgp Sgp
69 Sgp Sgp
70 Sgp Sgp
71 For Sgp
72 For Sgp
73 For Sgp
74 For Sgp
75 Ind Sgp
76 Sgp Sgp
77 Sgp Sgp
78 Sgp Sgp
79 Sgp Sgp
80 For Sgp
81 Sgp Sgp
82 For Sgp
83 For Sgp
84 Sgp Sgp
85 For Sgp
86 Sgp Sgp
87 For Sgp
88 For Sgp
89 For Sgp
90 Sgp Sgp
91 For For
92 For F

#FewShot

In [ ]:
def classifyFS(statement):
    response = client.chat.completions.create(
      model="gpt-4",
      messages=[
        {
          "role": "system",
          "content": 'You are a dialectologist specializing in English. Your job is to classify the dialect. The classification labels are:\
          1 = British dialect\
          2 = Singapore dialect\
          3 = Indian dialect\
          4 = Australian dialect\
          5 = South African dialect\
          6 = Irish dialect\
          0 = No dialect\
          Here are the sentences classified by English dialects:\
          "Mum said it made her depressed and bitter, and her husband left her because of it." - British English (Classified as 1).\
          "Eh, you very kiasu leh, always must be first in everything." - Singaporean English (Classified as 2).\
          "Side, please. I\'m in a hurry." - Indian English (Classified as 3).\
          "Tim is a bludger; he always tries to sneak his way out of difficult situations." - Australian English (Classified as 4).\
          "I\'ll see you just now; I\'m quickly going to the shop." - South African English (Classified as 5).\
          "We\'re just having a bit of craic at the party." - Irish English (Classified as 6).\
          For general english statements, (Classified as 0).\
          Just output the labels'
        },
        {
          "role": "user",
          "content": statement
        }
      ],
      temperature=0,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )
    time.sleep(1)
    #print(response.choices[0].message.content)
    label = re.sub("[^0-9]", "", response.choices[0].message.content)
    return label

#ChainOfThought

In [ ]:
def classify3(statement):
    response = client.chat.completions.create(
      model="gpt-4",
      messages=[
        {
          "role": "system",
          "content": 'You are a professional at classifying English as different dialects. Your job is to classify the dialect. The classification labels are:\
          1 = British dialect\
          2 = Singapore dialect\
          3 = Indian dialect\
          4 = Australian dialect\
          5 = South African dialect\
          6 = Irish dialect\
          0 = No dialect\
          A few examples of sentences classified by English dialects:\
          "Mum said it made her depressed and bitter, and her husband left her because of it." - British English (Classified as 1) because Mum is commonly used by a person from britain to address their mother, similarly Bonkers is used to assert than a person is mad or crazy.\
          "He drives so fast, quite scary sometimes." - Singaporean English (Classified as 2) because "quite" coming immediately after a comma is similar to how "sangat" is used in malay and follows the sentence structure of the other languages in the region\
          "Side, please. I\'m in a hurry." - Indian English (Classified as 3) because "Side, please" is very common phrase used in Indian to ask the general public to move out the way in a polite manner. Indian english also end the sentences abruptly such with term such as that\'s all, ok ya, this only no and so on.\
          "Tim is a bludger; he always tries to sneak his way out of difficult situations." - Australian English (Classified as 4) because the word bludger is used to refer to a lazy person, its commonly used by australian\'s.\
          "It\'s a bit chilling today, better than being hot though, isn\'t it?" - South African English (Classified as 5) because South Africans tend to use more double negatives to express themselves, most other dialects would have just use "right?" to end the sentence instead\
          "We\'re just having a bit of craic at the party." - Irish English (Classified as 6) because "criac" is Irish for having a good time and an irish accent tends to be more upbeat.\
          "Our aim is to minimize the effort to train the two-stage pipeline of the conventional teacher-student framework." - General English, (Classified as 0) because there is no specific term or pattern suggesting that it belongs a particular dialect.\
          DO NOT GENERATE ANY NEW CLASSIFICATION BEYOND WHAT\'s DESCRIBED ABOVE'
        },
        {
          "role": "user",
          "content": statement
        }
      ],
      temperature=0,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )
    time.sleep(1)
    print(response.choices[0].message.content)
    label = re.sub("[^0-9]", "", response.choices[0].message.content) #returns two labels if there are 2, returns 1 if there is only 1
    if len(label) < 2:
      return label
    else:
      return label[0:2]

In [ ]:
classify3("Oh jeez, I have something on right now")

This sentence could be classified as 4 - Australian dialect. The phrase "I have something on" is commonly used in Australian English to indicate that one is busy or has plans.


'4'

In [ ]:
accuracy = 0
diaAcc_chain = np.zeros((7,7))
labels=[]

In [ ]:
content = pd.read_csv("/content/datasetWAnno 1.csv", index_col=None, header=None)
for count, senLabPair in enumerate(content.values):
  if senLabPair[0] not in ['!','?','.']:
    senLabPair[0] += "."
  label = classify3(senLabPair[0])
  label1 = label[0]
  label2 = label[-1]
  label1 = dialectDict[label1]
  label2 = dialectDict[label2]
  labels.append((label1,label2))
  print(count+1, label1, label2, senLabPair[1], senLabPair[2])

This sentence is in Irish English (Classified as 6) because "grand" is a term commonly used in Ireland to describe something that is good or satisfactory.
1 Irs Irs
This sentence is classified as 6 - Irish dialect. The phrase "down at the pub" and "for a pint" are commonly used in Ireland.
2 Irs Irs
This sentence would be classified as British English (1) because "jumper" is a term commonly used in Britain to refer to a sweater or pullover.
3 Brt Irs
This sentence is in British English (Classified as 1) because "gobsmacked" is a term commonly used in Britain to express surprise or astonishment.
4 Brt Irs
This sentence is classified as 6, which represents the Irish dialect. The term "craic" is commonly used in Ireland to describe fun or entertainment.
5 Irs Irs
This sentence is in Irish English (Classified as 6) because "peckish" is a term commonly used in Ireland to describe feeling slightly hungry, and "Tayto crisps" is a popular brand of potato chips in Ireland.
6 Irs Irs
This senten

In [ ]:
#diaAcc_chain = np.zeros((7,7))
for count, senLabPair in enumerate(content.values):
  if labels[count][0] == senLabPair[1] or labels[count][1] == senLabPair[1] or \
  labels[count][0] == senLabPair[2] or labels[count][1] == senLabPair[2]:
      accuracy += 1
  #diaAcc_chain[int(reversedDict[senLabPair[1]])][int(reversedDict[labels[count][0]])] += 1

#print(diaAcc_chain)
accuracy_percentage = accuracy / len(content) * 100
print(accuracy_percentage)

[[30.  0.  0.  0.  0.  0.  0.]
 [ 3. 26.  0.  0.  0.  0.  1.]
 [ 8.  0. 19.  2.  0.  1.  0.]
 [ 3.  0.  0. 27.  0.  0.  0.]
 [ 0.  1.  0.  0. 29.  0.  0.]
 [ 9.  4.  1.  1.  1. 14.  0.]
 [ 8.  7.  0.  0.  1.  0. 14.]]
151.42857142857142


In [ ]:
file = open("ChainThoughtResultsNoMatrix.txt", "r")
labels = file.read().split('\n')[1:420:2]
labels = [label.split(' ')[0:3] for label in labels]
print(labels)
content = pd.read_csv("/content/datasetWAnno.csv", index_col=None, header=None)
accuracy = 0
for count, senLabPair in enumerate(content.values):
    label = labels[count][1]
    print(label, senLabPair[1], senLabPair[2])
    if label == senLabPair[1] or label == senLabPair[2]:
      accuracy += 1
accuracy_percentage = accuracy / len(content) * 100
print(accuracy_percentage)

[['1', 'Irs', 'Irs'], ['2', 'Irs', 'Irs'], ['3', 'Brt', 'Irs'], ['4', 'Brt', 'Irs'], ['5', 'Irs', 'Irs'], ['6', 'Irs', 'Irs'], ['7', 'Irs', 'Irs'], ['8', 'Irs', 'Irs'], ['9', 'Irs', 'Irs'], ['10', 'Irs', 'Irs'], ['11', 'Irs', 'Irs'], ['12', 'Irs', 'Irs'], ['13', 'Brt', 'Irs'], ['14', 'Irs', 'Irs'], ['15', 'Brt', 'Irs'], ['16', 'For', 'Irs'], ['17', 'Brt', 'Irs'], ['18', 'For', 'Irs'], ['19', 'Irs', 'Irs'], ['20', 'Brt', 'Irs'], ['21', 'For', 'Irs'], ['22', 'Ind', 'Irs'], ['23', 'Aus', 'Irs'], ['24', 'Aus', 'Irs'], ['25', 'For', 'Irs'], ['26', 'For', 'Irs'], ['27', 'For', 'Irs'], ['28', 'Irs', 'Irs'], ['29', 'Irs', 'Irs'], ['30', 'Brt', 'Irs'], ['31', 'Saf', 'Saf'], ['32', 'Saf', 'Saf'], ['33', 'Saf', 'Saf'], ['34', 'Aus', 'Saf'], ['35', 'Saf', 'Saf'], ['36', 'Saf', 'Saf'], ['37', 'Saf', 'Saf'], ['38', 'Saf', 'Saf'], ['39', 'For', 'Saf'], ['40', 'Saf', 'Saf'], ['41', 'Saf', 'Saf'], ['42', 'For', 'Saf'], ['43', 'Saf', 'Saf'], ['44', 'Brt', 'Saf'], ['45', 'Brt', 'Saf'], ['46', 'Brt', 'Saf

# Generator

#Zero shot generator

In [ ]:
def regenerate(statement, targetDialect):
    response = client.chat.completions.create(
      model="gpt-4",
      messages=[
        {
          "role": "system",
          "content": f"You are a dialectologist specializing in English. Your job is to translate the prompt sentence into {targetDialect} English.",
        },
        {
          "role": "user",
          "content": statement
        }
      ],
      temperature=0,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )

    #print(statement)
    #print(targetDialect+":",response.choices[0].message.content)
    return response.choices[0].message.content

In [ ]:
map = [2, 2, 3, 3, 4, 4, 5, 5, 6, 6,
       1, 1, 3, 3, 4, 4, 5, 5, 6, 6,
       1, 1, 2, 2, 4, 4, 5, 5, 6, 6,
       1, 1, 2, 2, 3, 3, 5, 5, 6, 6,
       1, 1, 2, 2, 3, 3, 4, 4, 6, 6,
       1, 1, 2, 2, 3, 3, 4, 4, 5, 5,]

In [ ]:
csvfile = "genSentences"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None, header=None)
responses = []
for count, senLabPair in enumerate(content.values):
    response = regenerate(senLabPair[0], dialectDict[int(map[count])])
    responses.append(response)
    print(count+1, senLabPair[0])
    print(dialectDict[map[count]]+":",response)

1 Sure, it's a grand day outside for a walk, isn't it?
South African: Sure, it's a lekker day outside for a walk, isn't it?
2 I'll meet you down at the pub later for a pint.
South African: I'll see you just now at the local for a dop.
3 We're just having a bit of craic at the party.
Singaporean: We just having some fun lah, at the party.
4 I'm feeling a bit peckish; could you pass the Tayto crisps?
Singaporean: I feeling a bit hungry lah; can pass the Tayto chips or not?
5 Would you be after stopping at the shop for some milk?
Australian: Would you be able to stop by the servo for some milk?
6 That film was brilliant, so it was.
Australian: That movie was bloody brilliant, mate.
7 I’ve a notion to bake some soda bread this afternoon, would you like some?
Indian: I'm thinking to make some soda bread this evening, would you fancy having some?
8 It's a soft day, thank God, just a light drizzle.
Indian: It's a gentle day, thank God, just a light sprinkle.
9 I'm after getting a new job in t

In [ ]:
csvfile = "genSentences"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None, header=None)
responses,tag = [],[]
for count, senLabPair in enumerate(content.values):
  response = regenerate(senLabPair[0], dialectDict[int(map[count])])
  responses.append(response)
  tag.append(dialectDict[int(map[count])])
  print(count+1, senLabPair[0])
  print(dialectDict[map[count]]+":",response)

1 Sure, it's a grand day outside for a walk, isn't it?
South African: Sure, it's a lekker day outside for a walk, isn't it?
2 I'll meet you down at the pub later for a pint.
South African: I'll meet you down at the shebeen just now for a dop.
3 We're just having a bit of craic at the party.
Singaporean: We're just playing around and enjoying at the party lah.
4 I'm feeling a bit peckish; could you pass the Tayto crisps?
Singaporean: I feeling a bit hungry lah; can pass the Tayto chips or not?
5 Would you be after stopping at the shop for some milk?
Australian: Would you mind popping into the shop for some milk?
6 That film was brilliant, so it was.
Australian: That movie was bloody brilliant, wasn't it?
7 I’ve a notion to bake some soda bread this afternoon, would you like some?
Indian: I'm getting an idea to make some soda bread this evening, would you like to have some?
8 It's a soft day, thank God, just a light drizzle.
Indian: By God's grace, it's a pleasant day, just a light rain 

In [ ]:
data = pd.DataFrame(content.values,columns=['Input','Class_I'])
data['Output'] = responses
data['Class_O'] = tag
data.to_csv("Outputfile.csv")

#Few Shot Generator

In [ ]:
exampleSentences = ["","","'I tried my level best to not be late da, but the traffic here is really bad'",
                    "'Bro, I tried to be on time, but the jam on the way here really cannot.'",
                    "'I usually make an effort to be punctual, but the traffic was absolutely bollocks pal.'",
                    "'Mate, I tried to be here on time, but the traffic was shocking today.'"]

In [ ]:
def regenerateFS(statement, targetDialect, exampleSentence):
    response = client.chat.completions.create(
      model="gpt-4",
      messages=[
        {
          "role": "system",
          "content": f"You are a dialectologist specializing in English. Your job is to translate the prompt sentence into {targetDialect} English.\
          Example, translating this sentences: 'Dude, I tried to be here on time, but the traffic is horrible.' to {exampleSentence}",
        },
        {
          "role": "user",
          "content": statement
        }
      ],
      temperature=1,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )

    #print(statement)
    #print(targetDialect+":",response.choices[0].message.content)
    return response.choices[0].message.content

In [ ]:
map = [3, 3, 4, 4, 5, 5, 6, 6,
       3, 3, 4, 4, 5, 5, 6, 6,
       4, 4, 4, 5, 5, 5, 6, 6, 6,
       3, 3, 3, 5, 5, 5, 6, 6, 6,
       3, 3, 3, 4, 4, 4, 6, 6, 6,
       3, 3, 3, 4, 4, 4, 5, 5, 5,]

In [ ]:
csvfile = "genSentencesAlt"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None, header=None)
responses,tag = [],[]
for count, senLabPair in enumerate(content.values):
  targetDialect = dialectDict[int(map[count])]
  exampleSentence = exampleSentences[int(map[count])-1]
  response = regenerateFS(senLabPair[0], targetDialect,exampleSentence)
  responses.append(response)
  tag.append(dialectDict[int(map[count])])
  print(count+1, senLabPair[0])
  print(dialectDict[map[count]]+":",response)

1 Sure, it's a grand day outside for a walk, isn't it?
Singaporean: Confirm, today's weather very shiok for jalan jalan, right?
2 I'll meet you down at the pub later for a pint.
Singaporean: Later I jio you go pub drink beer can?
3 We're just having a bit of craic at the party.
Australian: We're just having a bit of fun at the party.
4 I'm feeling a bit peckish; could you pass the Tayto crisps?
Australian: I'm feeling a bit hungry; could you pass the Smith's chips?
5 Would you be after stopping at the shop for some milk?
Indian: Would you mind stopping by the store for some milk, buddy?
6 That film was brilliant, so it was.
Indian: That movie was absolutely fantastic, seriously it was.
7 I’ve a notion to bake some soda bread this afternoon, would you like some?
British: I've a mind to knock up some soda bread this afternoon, fancy a bit?
8 It's a soft day, thank God, just a light drizzle.
British: It's a gentle day, thank goodness, just a light mizzle.
9 I'm just popping around the cor

In [ ]:
data = pd.DataFrame(content.values,columns=['Input','Class_I'])
data['Output'] = responses
data['Class_O'] = tag
data.to_csv("Outputfile.csv")

In [ ]:
exampleSentences = ["","","'I tried my level best to come on time, but the traffic was mad macha.' Indians commonly use terms such as da, macha are equivalent to mate, buddy, dude. Indians also use 'level best' to express that they have made an effort or trying hard to achieve something.",
                    "'Bro, I tried to be on time, but the jam on the way here really cannot.' Jam is a singlish way of addressing a traffic jam. Really cannot is also a singlish phrase that states that something is intolerable.",
                    "'I usually make an effort to be punctual, but the traffic was absolutely bollocks pal.' Britishers use pal, bloke are used to address a friend. Britishers also make use of bollocks to express that they disagree with something and just dismiss something they can't seem to believe.",
                    "'Mate, I tried to be here on time, but the traffic was shocking today.' Australians use mate to address a friend."]

In [ ]:
def regenerateCOT(statement, targetDialect, exampleSentence):
    response = client.chat.completions.create(
      model="gpt-4",
      messages=[
        {
          "role": "system",
          "content": f"You are a dialectologist specializing in English. Your job is to translate the prompt sentence into {targetDialect} English.\
          Example, translating this sentences: 'Dude, I tried to be here on time, but the traffic is horrible.' to {exampleSentence}. Explain the chain of thought and then translate the sentence",
        },
        {
          "role": "user",
          "content": statement
        }
      ],
      temperature=1,
      max_tokens=256,
      top_p=1,
      frequency_penalty=0,
      presence_penalty=0
    )

    #print(statement)
    #print(targetDialect+":",response.choices[0].message.content)
    return response.choices[0].message.content

In [ ]:
regenerateCOT("Accadaccas is something the Aussie feel proud of ,since it's a rock band that has its origins in Australia", 'Indian' ,"'I tried my level best to come on time, but the traffic was mad macha.' Indians commonly use terms such as da, macha are equivalent to mate, buddy, dude. Indians also use 'level best' to express that they have made an effort or trying hard to achieve something.")

"In Indian English, the term 'Accadaccas' might not be commonly recognized, as it is a colloquial term for the Australian rock band AC/DC. However, the sentiment of pride in a local or national achievement is universal. The term 'macha' is often used in Indian English as a term of camaraderie, similar to 'mate' or 'dude'. So, the sentence could be translated as: 'Macha, we feel so proud of Accadaccas, as it's a rock band that originated from our place.'"

In [ ]:
csvfile = "genSentencesAlt"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None, header=None)
responses,tag = [],[]
for count, senLabPair in enumerate(content.values):
  targetDialect = dialectDict[int(map[count])]
  exampleSentence = exampleSentences[int(map[count])-1]
  response = regenerateCOT(senLabPair[0], targetDialect,exampleSentence)
  responses.append(response)
  tag.append(dialectDict[int(map[count])])
  print(count+1, senLabPair[0])
  print(dialectDict[map[count]]+":",response)

1 Sure, it's a grand day outside for a walk, isn't it?
Singaporean: Eh, the weather outside quite good for jalan-jalan, right?

Reasoning: "Eh" is commonly used in Singaporean English (or Singlish) for calling attention. "Quite good" is a phrase often used by Singaporean to signify something is not just good, but quite satisfactory. "Jalan-jalan" is a Malay term used in Singlish meaning to "go for a walk". The word "right" at the end of the sentence is used as a question tag, which is commonly used by Singaporeans.
2 I'll meet you down at the pub later for a pint.
Singaporean: Later on I'll see you at the pub for a beer, okay? 

Singaporean English, often referred to colloquially as 'Singlish', is famed for its unique phrases and sentence structure. In this translation, "I'll meet you down" is made simpler to "I'll see you", as direct translations are more commonly used in Singlish. "For a pint" is translated to "for a beer" because 'a pint' is not as commonly used in Singaporean Engli

In [ ]:
csvfile = "gennedSentences"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None)

In [ ]:
content.values[0][4]

'South African'

In [ ]:
dialectDict[int('2')]

'South African'

#Only Indian and Singaporean Generation

In [ ]:
map = [5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3,]

In [ ]:
csvfile = "genSentencesIndSgp"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None, header=None)
responses,tag = [],[]
for count, senLabPair in enumerate(content.values):
    targetDialect = dialectDict[int(map[count])]
    response = regenerate(senLabPair[0], dialectDict[int(map[count])])
    responses.append(response)
    tag.append(dialectDict[int(map[count])])
    print(count+1, senLabPair[0])
    print(dialectDict[map[count]]+":",response)

1 We are having some mates over for a barbie sarvo, you should come!
Indian: We are having some friends over for a barbecue this afternoon, you should come!
2 He's a few roo's loose in the top paddock
Indian: He's a few sandwiches short of a picnic.
3 I'm muzzed after that afterparty, it was a ripper of a party
Indian: I'm totally zonked after that afterparty, it was a cracking good party.
4 Accadaccas is something the Aussie feel proud of ,since it’s a rock band that has its origins in Australia
Indian: Accadaccas is something the Aussies take pride in, yaar, because it's a rock band that started in Australia only.
5 It's Friday, usually a g'day to be on the piss with mates
Indian: It's Friday, typically a good day to have drinks with friends.
6 That film was brilliant, so it was.
Indian: That film was outstanding, isn't it?
7 I’ve a notion to bake some soda bread this afternoon, would you like some?
Indian: I'm having an idea to make some soda bread this evening, would you fancy some

In [ ]:
data = pd.DataFrame(content.values,columns=['Input','Class_I'])
data['Output'] = responses
data['Class_O'] = tag
data.to_csv("Outputfile.csv")

In [ ]:
exampleSentences = ["","","'I tried my level best to not be late da, but the traffic here is really bad.' Indians commonly use terms such as da, macha are equivalent to mate, buddy, dude. Indians also use 'level best' to express that they have made an effort or trying hard to achieve something.",
                    "'Bro, I tried to be on time, but the jam on the way here really cannot.' Jam is a singlish way of addressing a traffic jam. Really cannot is also a singlish phrase that states that something is intolerable.",
                    "'I usually make an effort to be punctual, but the traffic was absolutely bollocks pal.' Britishers use pal, bloke are used to address a friend. Britishers also make use of bollocks to express that they disagree with something and just dismiss something they can't seem to believe.",
                    "'Mate, I tried to be here on time, but the traffic was shocking today.' Australians use mate to address a friend."]

In [ ]:
csvfile = "genSentencesIndSgp"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None, header=None)
responses,tag = [],[]
for count, senLabPair in enumerate(content.values):
    targetDialect = dialectDict[int(map[count])]
    exampleSentence = exampleSentences[int(map[count])-1]
    response = regenerateCOT(senLabPair[0], targetDialect,exampleSentence)
    responses.append(response)
    tag.append(dialectDict[int(map[count])])
    print(count+1, senLabPair[0])
    print(dialectDict[map[count]]+":",response)

1 We are having some mates over for a barbie sarvo, you should come!
Indian: Indians generally use "friends" or "buddies" instead of "mates," and "barbecue" would be the full term used instead of "barbie." "Sarvo," meaning this afternoon, is an Australian term not typically found in Indian English. A more common way to say this in India might be "later today" or "this evening." Food parties are very common and loved in India, so this concept translates well.

So, in Indian English it could be: "We're having some friends over for a barbecue this evening. You should come!"
2 He's a few roo's loose in the top paddock
Indian: This Australian English idiom means that someone is not very intelligent or is behaving in a crazy manner. In Indian English, the concept of someone being not very wise can be conveyed with phrases like 'A bit dim in the head' or 'Not the brightest bulb'. Therefore, this sentence can be translated to Indian English as 'He's a bit dim in the head.'
3 I'm muzzed after t

In [ ]:
data = pd.DataFrame(content.values,columns=['Input','Class_I'])
data['Output'] = responses
data['Class_O'] = tag
data.to_csv("Outputfile.csv")

#Reclassifying the generated sentences

In [ ]:
accuracy = 0

In [ ]:
csvfile = "gennedSentences"
content = pd.read_csv(f"/content/{csvfile}.csv", index_col=None)
for count, senLabPair in enumerate(content.values):
  label = classify(senLabPair[3])
  print(senLabPair[3])
  try:
    label = dialectDict[label]
    print(count+1, label, senLabPair[4])
    if label == senLabPair[4]:
      accuracy += 1
  except KeyError as e:
      print(f"KeyError occurred: {e}")
      continue


Sure, it's a lekker day outside for a walk, isn't it?
1 Saf Saf
I'll meet you down at the shebeen just now for a dop.
2 Saf Saf
We're just playing around and enjoying at the party lah.
3 Sgp Sgp
I feeling a bit hungry lah; can pass the Tayto chips or not?
4 Sgp Sgp
Would you mind popping into the shop for some milk?
5 Brt Aus
That movie was bloody brilliant, wasn't it?
6 Brt Aus
I'm getting an idea to make some soda bread this evening, would you like to have some?
7 Irs Ind
By God's grace, it's a pleasant day, just a light rain is there.
8 Ind Ind
I've just secured a new job in the city, indeed I have.
9 Irs Brt
Let's have a little natter over a cup of tea, shall we?
10 Brt Brt
I'm just nipping 'round the corner to buy some biltong.
11 Saf Irs
This new project is quite grand, isn't it?

12 Brt Irs
I think we should barbecue this weekend if the weather is good.
13 For Sgp
I coming to see you soon lah, just need clear some work first.
14 Sgp Sgp
That film was bloody brilliant, wasn't it?

NameError: ignored

In [ ]:
accuracy_percentage = accuracy / len(content) * 100
print(accuracy_percentage)
print(accuracy)

55.00000000000001
33
